### ISSUE TITLE
Exception when query on collection that have partition key

### ISSUE THREAD

**Issue by meomeo0110** [Azure/azure-cosmosdb-spark#112]
Hi everyone;

I followed example: 
https://github.com/Azure/azure-cosmosdb-spark/wiki/Configuring-Power-BI-Direct-Query-to-Azure-Cosmos-DB-via-Apache-Spark-(HDI)
I could connect and create table that mapping Document DB collection successfully. However, every time I query collection that have partition key, there is a exception: `Server could not parse the Url., StatusCode: NotFound`
This exception did not happen, when I query on collection that does not have partition key.
Here is my connection string:
spark.sql("create table animal using com.microsoft.azure.cosmosdb.spark options (Endpoint '$Endpoint', Database 'planet', Collection '$Collection', Masterkey '$MasterKey', ConnectionMode 'Gateway')")

Would you like show me how to create a spark table that mapping collection with partition key?

Thanks

**Comment by khdang** [comment]
I think this is related to https://github.com/Azure/azure-cosmosdb-spark/issues/104 and should have been fixed with the latest release. Can you try again with the latest version 0.0.4? Feel free to reopen if this is still a problem.
