### ISSUE TITLE
no sqlContext in com.microsoft.azure.cosmosdb.spark

### ISSUE THREAD

**Issue by gypsysunny** [Azure/azure-cosmosdb-spark#120]
spark.sqlContext.read.cosmosDB(readConfig) doesn't work because there is no sqlContext in com.microsoft.azure.cosmosdb.spark.

i use azure-cosmosdb-spark_2.0.2_2.10 with the version of 0.03
anyone can help with that? thank you in advance.

**Comment by pyryjook** [comment]
How did you solve this? I'm facing the same error.
