### ISSUE TITLE
where can I set the offerThroughput in terms of this azure-cosmosdb-spark?

### ISSUE THREAD

**Issue by gypsysunny** [Azure/azure-cosmosdb-spark#122]
thanks.
i haven't found that.

**Comment by khdang** [comment]
@gypsysunny can you give us more details on what you are trying to achieve?

**Comment by khdang** [comment]
@gypsysunny since I haven't heard back from you, I'm closing this issue for now. Feel free to reopen and provide us with more details. Thanks!
