### ISSUE TITLE
spark.CosmosDBSpark.save(jsonRDD.toDS(), writeConfig)

### ISSUE THREAD

**Issue by gypsysunny** [Azure/azure-cosmosdb-spark#123]
this api can help to save json data to cosmosdb, but the format in the doc is not of json( i have produced the json format for the data before i try to save it).

**Comment by khdang** [comment]
I understand that you're saving an RDD of Json to CosmosDB and expect the Json to be saved as Document. Let me try to reproduce and fix this.

**Comment by khdang** [comment]
@gypsysunny Can you let us know how you create the jsonRDD? and what is the format of the json file?

**Comment by gypsysunny** [comment]
case class XObj(val id:String, val type: String, val info:String)
val jsonRDD = rdd.mapPartitions(partition => {
      implicit val formats: Formats = DefaultFormats
      while (partition.hasNext) {
        val line = partition.next()
        val id= line.getString(0)
        val xObj = ETAObj(id, "yType", "zInfo")
        val jsonResultStr = pretty(render(decompose(xObj ))) // net.liftweb.json
        jsonSet.add(jsonResultStr)
      }
      jsonSet.iterator
    })


the format is like this:
{
  "id":"111111",
  "type":"yType1",
  "Info":"zInfo1"
}
{
  "id":"22222",
  "type":"yType2",
  "Info":"zInfo2"
}

**Comment by khdang** [comment]
@gypsysunny can you check what is the schema of the jsonRdd? make sure that the schema is corresponding to the document structure you want. If you still have this issue, please let us know again.
