### ISSUE TITLE
Question: Does it only work with DocumentDB?

### ISSUE THREAD

**Issue by JayChandler** [Azure/azure-cosmosdb-spark#133]
Can this connector be used with the premium table api for cosmosdb ?

Thx

**Comment by dennyglee** [comment]
It's not officially supported yet but you should be able to do this.  Please refer to the blog post [Spark Connector for #CosmosDB - seamless interaction with globally-distributed, multi-model data](https://azure.microsoft.com/en-us/blog/spark-connector-for-cosmosdb-seamless-interaction-with-globally-distributed-multi-model-data/) and please refer to the section "Working with Azure Cosmos DB Tables".  HTH!

**Comment by khdang** [comment]
@JayChandler let us know if you run into any issues. Thanks!
