### ISSUE TITLE
The SDK reads all the data in memory when "changefeedstartfromthebeginning" flag is set to true

### ISSUE THREAD

**Issue by romitgirdhar** [Azure/azure-cosmosdb-spark#134]
Currently, the SDK attempts to read all the data into memory when the "changefeedstartfromthebeginning" flag is set. to true. Unless your spark job conf are set so that it can read all the data from your Cosmos DB collection, it will fail. 

As a potential fix, pagination option could be added to ChangeFeed when you use the "changefeedstartfromthebeginning" flag. This way, you don't have to hold all the data in memory.

**Comment by khdang** [comment]
Hey @romitgirdhar, this should be fixed with https://github.com/Azure/azure-cosmosdb-spark/commit/c3c0f5697823f6526fe779ff04c9f29329ffc6d5.
