### ISSUE TITLE
Struct Type Support broken?

### ISSUE THREAD

**Issue by ayanguha** [Azure/azure-cosmosdb-spark#140]
Hi

I have a df with following schema:
scala> df.printSchema()
root
 |-- id: string (nullable = true)
 |-- DocumentType: string (nullable = false)
 |-- PartyId: string (nullable = true)
 |-- PartyType: string (nullable = false)
 |-- PersonId: string (nullable = true)
 |-- PersonSource: string (nullable = false)
 |-- Gender: string (nullable = true)
 |-- BirthDate: string (nullable = true)
 |-- Name: struct (nullable = true)
 |    |-- Title: string (nullable = false)
 |    |-- GivenName: string (nullable = false)
 |    |-- FamilyName: string (nullable = false)
 |    |-- OtherNames: string (nullable = false)
 |    |-- FullName: string (nullable = false)
 |    |-- PreferredName: string (nullable = false)
 |    |-- NameSuffix: string (nullable = false)
 |-- memberships: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- id: string (nullable = true)
 |    |    |-- MembershipNumber: string (nullable = true)
 |    |    |-- RelationshipType: string (nullable = true)
 |    |    |-- Suffix: string (nullable = true)
 |    |    |-- IsCeased: string (nullable = true)
 |    |    |-- StartDate: string (nullable = true)
 |    |    |-- EndDate: string (nullable = true)
 |    |    |-- RoleTypes: string (nullable = true)
 |    |    |-- CommunicationPreferences: array (nullable = true)
 |    |    |    |-- element: struct (containsNull = true)
 |    |    |    |    |-- id: string (nullable = true)
 |    |    |    |    |-- Name: string (nullable = true)
 |    |    |    |    |-- ContactType: string (nullable = true)
 |    |    |    |    |-- PreferredContact: string (nullable = false)
 |    |    |    |    |-- CommunicationPreferenceType: string (nullable = true)
 |    |    |    |    |-- PreferenceType: string (nullable = true)
 |    |    |    |    |-- IsOptOut: string (nullable = true)
 |    |    |    |    |-- IsUnknown: string (nullable = true)
 |    |    |    |    |-- IsValid: string (nullable = true)
 |    |    |    |    |-- PreferredPostalAddress: struct (nullable = false)
 |    |    |    |    |    |-- Addressee: string (nullable = true)
 |    |    |    |    |    |-- AddressLine1: string (nullable = true)
 |    |    |    |    |    |-- AddressLine2: string (nullable = true)
 |    |    |    |    |    |-- AddressLine3: string (nullable = true)
 |    |    |    |    |    |-- Postcode: string (nullable = true)
 |    |    |    |    |    |-- State: string (nullable = true)
 |    |    |    |    |    |-- LocalityName: string (nullable = true)
 |-- PersonType: string (nullable = false)

Trying to write to Cosmos:

df.write.mode(SaveMode.Overwrite).cosmosDB(cosmosConfig)

This is how the cosmos config looks like:
val cosmosConfig = Config(Map("Endpoint" -> endpoint,
      "Masterkey" -> masterkey,
      "Database" -> database,
      "PreferredRegions" -> "Australia Southeast",
      "Collection" -> collection,
      "Upsert" -> "true",
      "SamplingRatio" -> "10.0",
      "schema_samplesize" -> "1"
    ))

Error:
Caused by: java.lang.Exception: Cannot cast 
[Some name,Some name,Some name,Some name,Some Full name,,] into a Json value. StructType(StructField(Title,StringType,false), StructField(GivenName,StringType,false), StructField(FamilyName,StringType,false), StructField(OtherNames,StringType,false), StructField(FullName,StringType,false), StructField(PreferredName,StringType,false), StructField(NameSuffix,StringType,false)) has no matching Json value.

  at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBRowConverter$.com$microsoft$azure$cosmosdb$spark$schema$CosmosDBRowConverter$$convertToJson(CosmosDBRowConverter.scala:147)
  at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBRowConverter$$anonfun$rowToDocument$1.apply(CosmosDBRowConverter.scala:123)
  at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBRowConverter$$anonfun$rowToDocument$1.apply(CosmosDBRowConverter.scala:121)

Wondering if I am missing something here?

**Comment by ayanguha** [comment]
This issue (Relevant in azure-cosmosdb-spark_2.0.2_2.11:0.0.3) is fixed in higher version (0.0.5). However, latest Maven release in Spark 2.0 series is 0.0.3, which may let people hit this issue still....

**Comment by dennyglee** [comment]
Thanks @ayanguha - we are currently on [1.0 release](https://mvnrepository.com/artifact/com.microsoft.azure/azure-cosmosdb-spark_2.2.0_2.11/1.0.0)  within Maven so we should be good to go.  Thanks!
