### ISSUE TITLE
CosmosDB sink error: 'write' can not be called on streaming Dataset/DataFrame

### ISSUE THREAD

**Issue by fbeltrao** [Azure/azure-cosmosdb-spark#147]
I am reading a data stream from Event Hub in Spark (using Databricks). My goal is to be able to write the streamed data to a CosmosDB. However I get the following error: org.apache.spark.sql.AnalysisException: 'write' can not be called on streaming Dataset/DataFrame.

Is this scenario not supported?

Spark versions: 2.2.0 and 2.3.0

Libraries used: 
- json-20140107 
- rxnetty-0.4.20 
- azure-documentdb-1.14.0 
- azure-documentdb-rx-0.9.0-rc2 
- azure-cosmosdb-spark_2.2.0_2.11-1.0.0 
- rxjava-1.3.0 
- azure-eventhubs-databricks_2.11-3.4.0

My code:
```scala
import com.microsoft.azure.cosmosdb.spark._
import com.microsoft.azure.cosmosdb.spark.schema._
import com.microsoft.azure.cosmosdb.spark.streaming._
import com.microsoft.azure.cosmosdb.spark.config._

import org.apache.spark.sql.SparkSession
import org.apache.spark.eventhubs.common.EventHubsUtils
import org.apache.spark.sql
import org.apache.spark.sql.functions._
import org.apache.spark.sql.types._
import org.apache.spark.sql.streaming.Trigger

val sparkConfiguration = EventHubsUtils.initializeSparkStreamingConfigurations

sparkConfiguration.setAppName("MeetupStructuredStreaming")
sparkConfiguration.set("spark.streaming.driver.writeAheadLog.allowBatching", "true")
sparkConfiguration.set("spark.streaming.driver.writeAheadLog.batchingTimeout", "60000")
sparkConfiguration.set("spark.streaming.receiver.writeAheadLog.enable", "true")
sparkConfiguration.set("spark.streaming.driver.writeAheadLog.closeFileAfterWrite", "true")
sparkConfiguration.set("spark.streaming.receiver.writeAheadLog.closeFileAfterWrite", "true")
sparkConfiguration.set("spark.streaming.stopGracefullyOnShutdown", "true")

val spark = SparkSession.builder().config(sparkConfiguration).getOrCreate()

val configMap = Map(
  "Endpoint" -> "https://xxx.documents.azure.com:443/",
  "Masterkey" -> "xxxx",
  "Database" -> "meetup",
  "Collection" -> "event"
)

val ehStream = spark.readStream  
  .format("eventhubs")
  .option("eventhubs.policyname", "xxx")
  .option("eventhubs.policykey", "xxx")
  .option("eventhubs.namespace", "xx")
  .option("eventhubs.name", "meetup")
  .option("eventhubs.partition.count", "2")
  .option("eventhubs.maxRate", "100")
  .option("eventhubs.consumergroup", "streaming")
  .option("eventhubs.progressTrackingDir", "/tmp/eventhub-progress/meetup-events")
  .option("eventhubs.sql.containsProperties", "true")        
  .load
  .select(
    from_unixtime(col("enqueuedTime").cast(LongType)).alias("enqueuedTime")
    , from_unixtime(get_json_object(col("body").cast(StringType), "$.mtime").divide(1000)).alias("time")
    , get_json_object(col("body").cast(StringType), "$.name").alias("name")
    , get_json_object(col("body").cast(StringType), "$.event_url").alias("url")
    , get_json_object(col("body").cast(StringType), "$.status").alias("status")
    , get_json_object(col("body").cast(StringType), "$.venue.country").alias("country")
    , get_json_object(col("body").cast(StringType), "$.venue.city").alias("city")
    , get_json_object(col("body").cast(StringType), "$.group.category.shortname").alias("category"))

var cosmosDbStreamWriter = ehStream
  .writeStream
  .outputMode("append")
  .format(classOf[CosmosDBSinkProvider].getName).options(configMap)  
  .option("checkpointLocation", "/tmp/streamingCheckpoint")
  .trigger(Trigger.ProcessingTime(1000 * 3)) // every 3 seconds  
  .start()
```

**Comment by dennyglee** [comment]
Hi @fbeltrao - what error are you getting when you write to Cosmos DB?  

Some quick notes:
* For the `cosmosDbStreamWriter` is referring to the eventHubs Stream, could you point it to a Cosmos DB write stream?
* The `configMap` also will need the `ChangeFeedCheckpointLocation` 

For more information, please check out [Replication Streaming to another collection](https://github.com/Azure/azure-cosmosdb-spark/wiki/Structured-Stream-demos#replication-streaming-to-another-collection).

**Comment by benjguin** [comment]
Hi @dennyglee, I have the same as @fbeltrao on a different project. I'm also trying to read from event hubs and write to Cosmos DB. My code is very similar to Francisco's. In my case, output mode is update (I didn't specify a watermark yet, so the append mode is not available). The stream starts and stops immediately with the same message: `org.apache.spark.sql.AnalysisException: 'write' can not be called on streaming Dataset/DataFrame; line 1 pos 0`

**Comment by dennyglee** [comment]
Apologies for the delayed response on this thread. We *think* we have identified the issue and resolved it in a recent PR. But before I say we’re done, let us run a few more tests to validate.  We did these as part of #187 and #188 where both EventHubs and the Cosmos DB connectors are using the developer API internalCreateDataframe.

**Comment by fbeltrao** [comment]
Hi @dennyglee,

Thanks for the update. 

I have written a way to stream to Cosmos DB while the bug fix is not available.
https://medium.com/@fbeltrao/an-introduction-to-spark-streaming-from-a-net-developer-d773a3275a73

**Comment by dennyglee** [comment]
Sorry for the delay, will get back to you shortly on this.

**Comment by mhamilton723** [comment]
Hey is there a PR with this fix?

**Comment by mhamilton723** [comment]
Hey, I just tried out the latest 2.3 branch and it seems like this is still an issue.

**Comment by mhamilton723** [comment]
Just tried on latest master, still seems to be occurring on databricks. @dennyglee Do you know if this is how one might go about fixing this? Thanks for your help!

**Comment by datamic** [comment]
@dennyglee  I get a similar issue with PySpark.  Is this the right format? and related bug?

cleanedBody.writeStream.format("com.microsoft.azure.cosmosdb.spark").outputMode('append').options(**writeConfig).start()

 Data source com.microsoft.azure.cosmosdb.spark does not support streamed writing

**Comment by francischeung** [comment]
I'm getting the same exception writing to DSE Cassandra from Azure Databricks Spark.

**Comment by pas725** [comment]
Hi @dennyglee , 

I am getting same issue as @fbeltrao.
In my case, reading from databricks delta and wrting it to cosmosDB.

Error : 

> org.apache.spark.sql.AnalysisException: 'write' can not be called on streaming Dataset/DataFrame;

Here is code sample.

`import com.microsoft.azure.cosmosdb.spark._
import com.microsoft.azure.cosmosdb.spark.schema._
import com.microsoft.azure.cosmosdb.spark.streaming._
import com.microsoft.azure.cosmosdb.spark.config._


import org.apache.spark.sql.functions._

    // Build connection string with the above information
 
    val  incomingStream = spark.readStream.format("delta").table("temp")

     val messages =
      incomingStream
      .withColumn("Offset", $"offset".cast(LongType))
      //.withColumn("Time (readable)", $"enqueuedTime".cast(TimestampType))
      //.withColumn("Timestamp", $"enqueuedTime".cast(LongType))
      .withColumn("Body", $"body".cast(StringType))
      //.withColumnRenamed("Time (readable)", "Time")
      .select("Offset", "Body")


    messages.printSchema 

    // Configure connection to the sink collection
    val map = Map("Endpoint" -> "***:443/",
    "Masterkey" -> "***==",
    "Database" -> "db",
    "Collection" -> "test-collection",
                             "PreferredRegions" -> "East US;",
    "WritingBatchSize" -> "100")
    val writeConfig = Config(map)

// Start the stream writer

    //messages.writeStream.outputMode("append").format("console").option("truncate", false).start().awaitTermination()

val streamingQueryWriter = messages.writeStream.format(classOf[CosmosDBSinkProvider].getName).outputMode("append").options(map).option("checkpointLocation", "streamingcheckpointlocation3jul").start()

`

Any updates ?

**Comment by kabirkhan** [comment]
Any update on this? Looks like it was fixed in source but the newest maven release as of July 11th 2018 still has the old code using dataframe.write. Any word on publishing a new maven version with this fix? I know there are workarounds, I'd just like to use the official package source

**Comment by kabirkhan** [comment]
Looks like the changes to fix this are only in 2.3 and didn't make their way into master @dennyglee

**Comment by tknandu** [comment]
@kabirkhan @pas725 @fbeltrao @benjguin @syedhassaanahmed @mhamilton723 @datamic @francischeung This is fixed - We've released new version of the Cosmos DB Spark connector targeting Spark 2.3 on Maven (https://search.maven.org/#artifactdetails%7Ccom.microsoft.azure%7Cazure-cosmosdb-spark_2.3.0_2.11%7C1.2.0%7Cjar)

**Comment by kabirkhan** [comment]
Awesome! Thanks!

**Comment by syedhassaanahmed** [comment]
Has anyone tried the latest connector? @tknandu After attaching `com.microsoft.azure:azure-cosmosdb-spark_2.3.0_2.11:1.2.0` I'm getting below exception, even though I've explicitly imported `com.microsoft.azure.cosmosdb.Document`
```
java.lang.NoClassDefFoundError: Could not initialize class com.microsoft.azure.cosmosdb.Document
```

Here is the code
```scala
import com.microsoft.azure.cosmosdb.spark._
import com.microsoft.azure.cosmosdb.spark.schema._
import com.microsoft.azure.cosmosdb.spark.streaming._
import com.microsoft.azure.cosmosdb.spark.config._
import com.microsoft.azure.cosmosdb.Document

val cosmosConf = Map(
  "Endpoint" -> "https://<endpoint>.documents.azure.com:443/",
  "Masterkey" -> "<master_key>",
  "Database" -> "testdb",
  "Collection" -> "testcoll",
  "Upsert" -> "true"
)

val cosmosDbStreamWriter = ehStream
  .writeStream
  .outputMode("append")
  .format(classOf[CosmosDBSinkProvider].getName)
  .options(cosmosConf)
  .option("checkpointLocation", "/tmp/streamingCheckpoint")
  .start()
```

**Comment by syedhassaanahmed** [comment]
@tknandu Update on above issue. Its related to #226 I specified the Cosmos DB Connector using Maven coordinates. After removing that one and uploading the [uber jar](http://repo1.maven.org/maven2/com/microsoft/azure/azure-cosmosdb-spark_2.3.0_2.11/1.2.0/) it works now. Thanks

**Comment by cfarre** [comment]
can you tell me why we are not able to use the jars from maven coordinates for com.microsoft.azure:azure-cosmosdb-spark_2.3.0_2.11:1.2.0? why this jar does not contain all the dependencies? we are not able to write with .writeStream
  .outputMode("append").format(classOf[CosmosDBSinkProvider].getName). It only works with the uber jar. It only works with uber jar. With jar from maven coordinates we get java.lang.NoClassDefFoundError: Could not initialize class com.microsoft.azure.cosmosdb.Document

**Comment by thunfischtoast** [comment]
I could not get it to work on Azure Databricks with either the Maven-versions nor uploading the uber jars . I always get the

```java.lang.UnsupportedOperationException: Data source com.microsoft.azure.cosmosdb.spark does not support streamed writing```

As a workaround I use the ```pyDocumentDB``` Python package, which can be used as follows:

```
import pydocumentdb
from pydocumentdb import document_client
from pydocumentdb import documents

cosmosConnectionPolicy = documents.ConnectionPolicy()
cosmosConnectionPolicy.EnableEndpointDiscovery = True
cosmosMasterKey = '<master key goes here>' 
cosmosHost = 'https://<some url>.azure.com:443/'
cosmosClient = document_client.DocumentClient(cosmosHost, {'masterKey': cosmosMasterKey}, cosmosConnectionPolicy)

def push_to_cosmos(row):
  cosmosClient.CreateDocument("dbs/<database name>/colls/<collection name>/", row.asDict())

<somedatastream>.writeStream.foreach(push_to_cosmos).start()
```

**Comment by nzregs** [comment]
i got mine to work with the "uber jar" but not maven.  I had to uninstall previous maven lib from cluster, upload/install the uber jar, and then **restart the cluster** (failed if I did not restart first)
