### ISSUE TITLE
Aggregates not Working (specifically Distinct)

### ISSUE THREAD

**Issue by jkergosi** [Azure/azure-cosmosdb-spark#151]
Cosmos DB is supposed to support Aggregates (specifically I'm trying Distnct), but it errors when trying:

Query: 
Select Distinct c.id
From c

Returns: 
Syntax error, incorrect syntax near 'Distinct'

References:
- In this post: https://github.com/Azure/azure-cosmosdb-spark/wiki  it states "Azure Cosmos DB has aggregations (SUM, MIN, MAX, COUNT, SUM and working on GROUP BY, DISTINCT, etc.)"

- https://azure.microsoft.com/en-us/updates/azure-documentdb-now-supports-aggregate-functions/

- https://github.com/Azure/azure-cosmosdb-spark/wiki/Aggregations-Examples Though it references Apache Spark, it clearly says "Azure Cosmos DB already has support for aggregations (link to blog goes here)"  (note the lack of the actual link. though...)

Please advise.

Note: Aggregates are pretty important. Frankly, this (as well as lack of skip) may be deal breakers for me.

**Comment by nomiero** [comment]
Distinct is currently supported, does this work for you now ?
