### ISSUE TITLE
Reading cosmos DB change feed in azure databricks

### ISSUE THREAD

**Issue by jcsclement** [Azure/azure-cosmosdb-spark#152]
@heyyjudes is it possible to add on how to configure and read Cosmos DB change feed in azure databricks spark stream? I ran into this [issue](https://forums.databricks.com/questions/13331/configure-un-supported-magic-command.html)

**Comment by thelazydogsback** [comment]
Ping...

**Comment by nomiero** [comment]
You can find streaming sample here 
https://docs.microsoft.com/en-us/azure/cosmos-db/spark-connector#write-twitter-data-that-is-streaming-to-azure-cosmos-db
