### ISSUE TITLE
How to write a graph to Graph CosmosDB in Spark

### ISSUE THREAD

**Issue by pl7y** [Azure/azure-cosmosdb-spark#155]
I don't know if I am missing something, but I couldn't find a single example of writing a graph to CosmosDB (which I thought would be one of the cases this lib is for).

Use Case: create a big-data graph from from historical data in flat files, using batch spark.

I tried Gremlin-scala, GraphX and GraphFrames but none of their `Graph`s has a "write" mechanism on Graph object. Is there a way to do this from Spark?

Anyway, thank you very much for effort and patience put in this library anyway.

**Comment by nomiero** [comment]
You can use GraphFrames using 
https://medium.com/@hasssaaannn/writing-apache-spark-graphframes-to-azure-cosmos-db-dcae3e436966
