### ISSUE TITLE
DataFrame did not have isSTreaming=true

### ISSUE THREAD

**Issue by unaizorrilla** [Azure/azure-cosmosdb-spark#174]
Trying to execute the notebook on samples ,https://github.com/Azure/azure-cosmosdb-spark/blob/master/samples/lambda/Streaming%20Query%20from%20Cosmos%20DB%20Change%20Feed.scala, the execution result on exception:

Stream stopped...

java.lang.AssertionError: assertion failed: DataFrame returned by getBatch from com.microsoft.azure.cosmosdb.spark.streaming.CosmosDBSource@280658d did not have isStreaming=true

Any ideas?

**Comment by dennyglee** [comment]
Hi @unaizorrilla - by any chance are you running this on Spark 2.3 or Azure Dtabricks?

**Comment by Xabaril** [comment]
In Azure Databricks using latest version!! I see you this sample on latest mvp summit using satanbricks

**Comment by unaizorrilla** [comment]
Hi @dennyglee , i’m sorry, I responde from another github account. Yes I try this sample on Azure Databricks. Any issue with this? I see this demo (cosmos Levi streaming for lambda arch) on your #mvpit session and this works without any problem

**Comment by dennyglee** [comment]
No worries - it does work within HDI / Jupyter notebooks because HDI is currently on Spark 2.1.  Within Azure Databricks, the default is Spark 2.3 and it introduced a change with IsStreaming=True.  We're working to resolve this and I had meant to create a GitHub issue, but forgot to - so thanks for that :).  Will keep you updated on our progress for this.

**Comment by mhamilton723** [comment]
Hey @dennyglee, 

I am a fellow microsoft employee who is running into this issue myself though on my own streaming adapters. Do you know how to fix this issue within your adapter? I believe your fix will also be the fix I am also searching for.

**Comment by tknandu** [comment]
Hey @mhamilton723 we have a PR out to solve this - you can take a look at https://github.com/Azure/azure-cosmosdb-spark/pull/183

PS. Which connector do you work on?

**Comment by mhamilton723** [comment]
Thanks for quick help! Thankfully it worked! I work on the [MMLSpark library](https://github.com/Azure/mmlspark/), which is Microsoft's open source initiative in distributed machine learning.

More specifically, we have a set of streaming sources and sinks that turn structured streaming into a web services. For deploying ML models and other spark computations.

**Comment by prashkdbg** [comment]
Hi All,
Any timelines when we can expect it to be resolved.
I am using databricks 4.0 (includes Apache Spark 2.3.0, Scala 2.11)

**Comment by tknandu** [comment]
@prashkdbg If you build the 2.3 branch, it will work!

**Comment by TheovanKraay** [comment]
Hi - getting the same error as mentioned initially (using Databricks). I can't get this working on any of the currently available maven repos (I don't see a 2.3) or versions of Databricks. Is there a combination that works?

**Comment by tknandu** [comment]
We've released new version of the Cosmos DB Spark connector targeting Spark 2.3 on Maven (https://search.maven.org/#artifactdetails%7Ccom.microsoft.azure%7Cazure-cosmosdb-spark_2.3.0_2.11%7C1.2.0%7Cjar)

**Comment by JorisvdK** [comment]
As far as I can tell, this does work yet, despite the release mentioned above. 

I'm using a notebook Azure Databricks 4.0 (includes Apache Spark 2.3.0, Scala 2.11) and have tried both azure-cosmosdb-spark_2.3.0_2.11-1.2.0 and azure-cosmosdb-spark_2.2.0_2.11_1.1.1

I'm trying to read from one Azure Cosmos DB to another, and the stream prints to the console, yet does not write to the second Azure Cosmos DB. It provides the error mentioned earlier:

java.lang.AssertionError: assertion failed: DataFrame returned by getBatch from com.microsoft.azure.cosmosdb.spark.streaming.CosmosDBSource@3eb222b0 did not have isStreaming=true
