### ISSUE TITLE
Appending duplicate records does not log error 

### ISSUE THREAD

**Issue by rajeevsinghAD** [Azure/azure-cosmosdb-spark#189]
Trying to execute a test case where we insert records which already exist in collection using df.write.mode(SaveMode.Append).cosmosDB(writeConfig). 
Earlier with azure-cosmosdb-spark_2.1.0_2.11-1.0.0.jar the spark job use to fail with following error

> 18/04/04 07:20:11 INFO TaskSetManager: Starting task 0.2 in stage 0.0 (TID 2, 10.75.169.23, executor 1, partition 0, PROCESS_LOCAL, 6561 bytes) 18/04/04 07:20:11 WARN TaskSetManager: Lost task 0.2 in stage 0.0 (TID 2, 10.75.169.23, executor 1): java.lang.RuntimeException: com.microsoft.azure.documentdb.DocumentClientException: \{"Errors":["Resource with specified id or name already exists."]} ActivityId: ef4ffa79-878e-4fc7-aee2-6cf662df3675, Request URI: /apps/0afbd294-5e16-481b-9b7c-1e59d784f362/services/3a30d1ba-9676-4050-8ff1-7dcddcadf652/partitions/ca4b8942-009c-4ac0-88dd-cdb421266423/replicas/131647611197783589p//, StatusCode: Conflict at cosmosdb_connector_shaded.rx.exceptions.Exceptions.propagate(Exceptions.java:57)

With new version  azure-cosmosdb-spark_2.1.0_2.11-1.1.0.jar, spark job succeeds but it does not log any error for the rejected records. 

Ideally spark job should succeed but with proper error messages in logs for rejected records.

**Comment by nomiero** [comment]
In the latest connector version 1.3.3 if your dataframe row has the same id, partition key combination while not have upsert config to true, you will get a conflict error back.

**Comment by inderjeetwadhwa** [comment]
what is the behavior for batch write
