### ISSUE TITLE
Support for collection name override at runtime (CosmosDBOutputRDD)

### ISSUE THREAD

**Issue by EronWright** [Azure/azure-cosmosdb-spark#198]
`CosmosDBOutputRDD` obtains the collection name via a Spark configuration property, and it would be nice to supply an override at runtime, e.g. via the `Configuration` object passed to `writeGraphRDD`.  This would make it possible to write a notebook that wrote to a specific graph, without the need to reconfigure the associated Spark cluster (which may be used by numerous notebooks).

Note that it is not generally possible to change the `SparkContext` configuration on a per-notebook basis.

**Comment by nomiero** [comment]
You can always use a map and override the collection config value with every write operation
Does that answer your request or is it something different ?
