### ISSUE TITLE
Data Loss when writing From Databricks to Cosmos db Graph

### ISSUE THREAD

**Issue by saksham123-sophos** [Azure/azure-cosmosdb-spark#199]
I am working on a project when relational database data needs to be converted into a graph database. I am creating dataframes in spark databricks and writing them to cosmos db . But all records are not reaching the destination . I had a file with 800k records , but 25k records are lost. I tried several times but there is loss of 25k records everytime. I am unable to find any reason behind this. Please have a look into this.

**Comment by tknandu** [comment]
@saksham123-sophos There was a transient check-in which caused this regression - we have checked in fix. If you build from source now, you will not see any issue - we will be releasing new versions soon. Which Spark connector were you using?
