### ISSUE TITLE
Conflicting default values for  “query_maxretrywaittimeinseconds” and “query_maxretryattemptsonthrottledrequests”

### ISSUE THREAD

**Issue by saravp123** [Azure/azure-cosmosdb-spark#238]
As per this document the default vales for below parameters are
“query_maxretrywaittimeinseconds” = 30
“query_maxretryattemptsonthrottledrequests” = 9.

But according to https://docs.microsoft.com/en-us/azure/cosmos-db/spark-connector, the default values are
“query_maxretrywaittimeinseconds” = 1000
“query_maxretryattemptsonthrottledrequests” = 1000.

Can you please let me know which one is correct?

**Comment by nomiero** [comment]
The defaults are 1000, 1000 
You can look at the source of truth here 
https://github.com/Azure/azure-cosmosdb-spark/blob/2.3/src/main/scala/com/microsoft/azure/cosmosdb/spark/config/CosmosDBConfig.scala#L129

Can you point me to where the document mentions that 
“query_maxretrywaittimeinseconds” = 30
“query_maxretryattemptsonthrottledrequests” = 9.
?

**Comment by saravp123** [comment]
Hi nomiero,

The document https://docs.microsoft.com/en-us/azure/cosmos-db/spark-connector initially had the default values as 30 and 9.  Sneha Gunda fixed the defaults to 1000, 1000 in this document yesterday
