### ISSUE TITLE
conflicting cross-version suffixes from Maven

### ISSUE THREAD

**Issue by howardatwork** [Azure/azure-cosmosdb-spark#239]
Added this to my Spark application build.sbt:
```
libraryDependencies += "com.microsoft.azure" %% "azure-cosmosdb-spark_2.1.0" % "1.2.2"
```
Getting:
```
[error] Modules were resolved with conflicting cross-version suffixes in ...:
[error]    org.apache.spark:spark-launcher _2.11, _2.10
[error]    org.json4s:json4s-ast _2.11, _2.10
[error]    org.apache.spark:spark-network-shuffle _2.11, _2.10
[error]    com.twitter:chill _2.11, _2.10
[error]    org.json4s:json4s-jackson _2.11, _2.10
[error]    com.fasterxml.jackson.module:jackson-module-scala _2.11, _2.10
[error]    org.json4s:json4s-core _2.11, _2.10
[error]    org.apache.spark:spark-unsafe _2.11, _2.10
[error]    org.apache.spark:spark-core _2.11, _2.10
[error]    org.apache.spark:spark-network-common _2.11, _2.10
[trace] Stack trace suppressed: run last *:update for the full output.
```
I'm using Spark 2.1.1. Looks like the dependencies linked to the connector has Scala 2.10.
Also the links on the Readme are not correct.

**Comment by FabianMeiswinkel** [comment]
There is a workaround that can be used to mitigate this conflict.

The **highlighted** changes in build.sbt will resolve the conflicting dependencies to Scala 2.10 and 2.11

[…]
 
scalaVersion := "2.11.8"
 
**libraryDependencies ++= Seq(
  "org.apache.spark" %% "spark-core" % "2.1.0" % "provided" ,
  "org.apache.spark" %% "spark-sql" % "2.1.0" % "provided"
)**
 
libraryDependencies += "com.microsoft.azure" % "azure-cosmosdb-spark_2.1.0_2.11" % "1.2.6" **% "provided" exclude("org.apache.spark", "spark-core_2.10")**
 
[…]

**Comment by FabianMeiswinkel** [comment]
Workaround confirmed to unblock.
