### ISSUE TITLE
How to write records with TTL?

### ISSUE THREAD

**Issue by kmalachowski** [Azure/azure-cosmosdb-spark#241]
Hi,
I'm trying to find a way for setting TTL at records level.
Could you give me some tip how to achieve that?

Best regards
Kamil

**Comment by tknandu** [comment]
Hi Kamil,

 As of today, you can set TTL at collection level external to the Cosmos DB Spark connector. Could you provide more context around how you want to set TTL (at document level?). We can then take it up as a feature ask

**Comment by nomiero** [comment]
You can also set the ttl property at the dataframe and it will be stored in the document and used for the ttl of the document
Details are here
https://docs.microsoft.com/en-us/azure/cosmos-db/time-to-live
