### ISSUE TITLE
Add custom JSON serializer option to structured stream connector

### ISSUE THREAD

**Issue by thiago-farias** [Azure/azure-cosmosdb-spark#252]
Hi, I'm struggling to write google protobuf objects into a CosmosDB using the spark structured stream connector without success. The underlying issue is that the data classes are generated by the protobuf compiler, and the default serialization (using the `CosmosDBRowConverter` object) is unable to serialize protobuf instances.
 
It would be nice if I could set a custom object serializer as an option that `org.apache.spark.sql.cosmosdb.util.StreamingWriteTask` can understand and use to write a `Document` instance, instead of using the default `CosmosDBRowConverter`.
It could be a trait like:
```
trait CustomJsonSerializer[A] {
   def toJsonString(value: A): String
}
```
Is there any plans to add such support? If not, can I submit a pull request?

**Comment by nomiero** [comment]
We currently don't have support for custom serializers but you are more than welcome to submit a pull request and we will take a look at it. 
Can you elaborate on what errors you see with protobuff objects ?
