### ISSUE TITLE
Join operation in 'query_custom'

### ISSUE THREAD

**Issue by sagartoms** [Azure/azure-cosmosdb-spark#254]
Hi,
Is join operation is supported for cosmos db in 'query_custom' configuration? 
I am using spark scala to read a collection from cosmos. I need to join another collection, so that i can use the where clause to filter data after joining the table.

**Comment by nomiero** [comment]
Join is currently not supported in cosmos db custom query 
This is what is currently supported in our sql syntax https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-sql-query

You will have to do the filter in query_custom without join and then use spark sql to execute the joins
