### ISSUE TITLE
impossible to push a StrucType to cosmos db

### ISSUE THREAD

**Issue by Alexkuva** [Azure/azure-cosmosdb-spark#255]
I'm having an issue when I want to add a structype column.

For the following schema, I can't stream to cosmos db:

`streamdata.printSchema()`
root
 |-- enqueuedTime: string (nullable = true)
 |-- time: string (nullable = true)
 |-- temperature: string (nullable = true)
 |-- localisation: struct (nullable = true)
 |    |-- type: string (nullable = true)
 |    |-- coordinates: array (nullable = true)
 |    |    |-- element: double (containsNull = true)
 |-- id: string (nullable = true)

When launching the stream, I've got the following error:

`streamdata.select("id","temperature","enqueuedTime","localisation")
  .writeStream
  .format(classOf[CosmosDBSinkProvider].getName)
  .outputMode("append")
  .options(sinkConfigMap)
  .option("checkpointLocation", "/tmp/streamingTelemetryTestPlop")
  .start`

org.apache.spark.SparkException: Job aborted due to stage failure: Task 3 in stage 58.0 failed 4 times, most recent failure: Lost task 3.3 in stage 58.0 (TID 246, 10.139.64.4, executor 1): java.lang.ClassCastException: org.apache.spark.sql.catalyst.expressions.UnsafeRow cannot be cast to

Do you have any idea to push a structype in cosmos db ?

Thank you in advance.

**Comment by FabianMeiswinkel** [comment]
This change has been included in the recently published version azure-cosmosdb-spark_2.3.0_2.11-1.3.1. You can also resolve the Maven coordinates in Databricks now instead of using the manually uploaded Uber jar. Just make sure to also add one of the slf4j bindings.
