### ISSUE TITLE
Exporting to CosmosDB sometimes fails because using old connection values

### ISSUE THREAD

**Issue by roalexan** [Azure/azure-cosmosdb-spark#268]
**Summary**

I wish that I could consistently reproduce this, but the gist is that in my testing I create and destroy various instances of resources, such as CosmosDB. I noticed that despite having connection information pointing to my latest instance of CosmosDB, it would sometimes fail with output indicating that it was trying to export to an older, delete instance. The resolution is to result the cluster. Is this expected behavior? A bad cache issue?

**Prerequisite**

An Azure CosmosDB (SQL API) account with a database **recommendations** and a collection **Users**.

**Notebook Python Code**

df = spark.createDataFrame([(1,  "Jack"), (2, "Kack"), (3, "Lack")], ["uid", "uname"])
#display(df)
writeConfig = {
 "Endpoint" : "https://**rba7**-sql.documents.azure.com:443/",
 "Masterkey" : "GMpk***RJAA==",
 "Database" : "recommendations",
 "Collection" : "Users",
 "Upsert" : "true"
}
df.write.format("com.microsoft.azure.cosmosdb.spark").options(**writeConfig).save()

**Expected Behavior**

Write the rows to the CosmosDB collection.

**Observed Behavior**

com.microsoft.azure.documentdb.DocumentClientException: java.net.UnknownHostException: **rba6**-sql.documents.azure.com: Name or service not known.

**Workaround**

Restart cluster.

**Comment by nomiero** [comment]
What is the version of the connector you are using and what is the spark runtime version ?

**Comment by devfiremonster** [comment]
From portal: DataBricks Runtime Version: 4.1 (includes Apache Spark 2.3.0, Scala 2.11). Library: Users/roalexan@microsoft.com/azure-cosmosdb-spark_2.3.0_2.11-1.2.2-uber.jar

**Comment by roalexan** [comment]
From portal: DataBricks Runtime Version: 4.1 (includes Apache Spark 2.3.0, Scala 2.11). Library: Users/roalexan@microsoft.com/azure-cosmosdb-spark_2.3.0_2.11-1.2.2-uber.jar

**Comment by LimeyJohnson** [comment]
I am seeing this same issue. 
Databricks: 4.1 (includes Apache Spark 2.3.0, Scala 2.11)
Library: azure-cosmosdb-spark_2.3.0_2.11-1.2.6-uber.jar

**Comment by nomiero** [comment]
Hey vchalmel,

The error you mentioned above is expected in versions < 1.2.7 because it was allowing only one connection string per spark session. Starting from 1.2.7, you can use it with multiple hosts with the same session.

**Comment by vchalmel** [comment]
@nomiero I have to underline that the homepage readme.md currently links to 1.2.2 as the reference "uber jar" ?
