### ISSUE TITLE
Structured streaming write succeeds, but no documents

### ISSUE THREAD

**Issue by chris-rs** [Azure/azure-cosmosdb-spark#275]
I'm using Spark 2.2 with the uber jar for cosmos: azure-cosmosdb-spark_2.2.0_2.11

I configured Cosmos as sink in a structured streaming app. The app succeeds without any exceptions and I see expected output in the console. But when I try to use the Data Browser in Azure Portal I see not any documents. In the messages panel I see an error after I do a refresh in the document viewer:  
{"code":400,"body":"Command find failed: Unknown server error occurred when processing this request.."}.

This is basically my sink:
```
dataset
            .toDF()
            .select("usr", "env", "col1", "col2", "col3", "col4")
            .writeStream
            .format(classOf[CosmosDBSinkProvider].getName)
            .outputMode("append")
            .options(Map(
                "Endpoint" -> ENDPOINT",
                "Masterkey" -> "KEY",
                "Database" -> "DB",
                "Collection" -> "COLL",
                "ChangeFeedCheckpointLocation" -> "/tmp/cp-cosmos",
                "ChangeFeedQueryName" -> "Cosmos sink"
            ))
            .option("checkpointLocation", "/tmp/cp-cosmos")
            .start()
```

**Comment by chris-rs** [comment]
I figured it out myself. I assumed (wrongly) that Cosmos DB allows both its native and Mongo API but if you choose for Mongo API you can only communicate by using this API.

In my case (from a microservices environment) different components have different tech stacks. For Java/Scala there is native Cosmos support, but for PHP you have to use Mongo API. So I tried both API's.

Solution (for now): Stick to the API you chose. Hopefully MS will improve Cosmos DB by allowing multi interfaces in the future.

**Comment by nomiero** [comment]
This is by design that the connector only works for sql API
