### ISSUE TITLE
java.lang.NoSuchMethodError with 1.3.2

### ISSUE THREAD

**Issue by yorek** [Azure/azure-cosmosdb-spark#279]
Just tried the latest release available on Maven (1.3.2). When using structured streaming to write to cosmosdb I get the following error:

org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 4.0 failed 4 times, most recent failure: Lost task 1.3 in stage 4.0 (TID 26, 10.139.64.6, executor 0): java.lang.NoSuchMethodError: com.microsoft.azure.cosmosdb.rx.AsyncDocumentClient.createDocument(Ljava/lang/String;Ljava/lang/Object;Lcom/microsoft/azure/cosmosdb/RequestOptions;Z)Lrx/Observable;

**Comment by nomiero** [comment]
Have you tried with the latest version 1.3.3 with the uber jar 
https://search.maven.org/remotecontent?filepath=com/microsoft/azure/azure-cosmosdb-spark_2.3.0_2.11/1.3.3/azure-cosmosdb-spark_2.3.0_2.11-1.3.3-uber.jar
I just tried with that and it worked fine.
There is a bug in using the maven coordinates without the uber jar and we are working on fixing that.
If it still doesn't work, can you send the sample spark script ?

**Comment by yorek** [comment]
I'll try with to uber jar right now. Problem is that using the uber jar make DevOps a little more tricky as you can just point to the maven coordinates. hopefully the fix for that will come soon! thanks :)

**Comment by yorek** [comment]
With the uber jar now everything is working, thanks
