### ISSUE TITLE
Release notes please?

### ISSUE THREAD

**Issue by yorek** [Azure/azure-cosmosdb-spark#280]
I've noticed that in the last days a lot of new released has been made available on Maven. Can you please document what is contained in such releases? There aren't any release notes available somewhere.

**Comment by nomiero** [comment]
Hey Yorek,

we started adding release notes from 1.3.3 to the wiki 
https://github.com/Azure/azure-cosmosdb-spark/wiki/Release-notes

We will also add this as park of the repo in the following releases

**Comment by yorek** [comment]
Great, thanks
