### ISSUE TITLE
Writes to cosmosdb loops & never succeeds nor fails when partition key is nested

### ISSUE THREAD

**Issue by vchalmel** [Azure/azure-cosmosdb-spark#283]
I'm using pyspark / databricks to E.T.L data from parquet files to CosmosDB (documentdb api).

Despite a first successful test with 5 rows of data, every following try to write data in cosmosdb just goes nowhere. Even with only one row, it just runs forever. When monitoring cosmosdb there is a regular, constant, flow of writing requests displayed in the "metrics" interface to the correct collection, but nothing is written.

In the spark stage details stderr I have a bunch of WARN level entries 
GoneAndRetryWithRetryPolicy: Received gone exception after backoff/retry. Will fail the request
com.microsoft.azure.documentdb.DocumentClientException: {"Errors":["The requested resource is no longer available at the server."]}

I don't even know how to find the issue there.

config :

writeConfigUL = {
    "Endpoint" : "",
    "Masterkey" : "",
    "Database" : "INSEE_SIRENE",
    "Collection" : "unitesLegales",
    "WritingBatchSize" : 500,
    "Upsert" : "true"
}
using azure_cosmosdb_spark_2_3_0_2_11_1_2_7_uber.jar

After further experimentation, this behaviour is triggered by a nested partition key ex defining it as "/partition/key" while creating the collection and the dataset in spark having a "key" field in a "partition" struct.

**Comment by lcsmith02** [comment]
Hi, I am from the CosmosDB team. Could you provide me an example of a document you're trying to insert?

**Comment by FabianMeiswinkel** [comment]
Nested partition keys are supported now in the [latest version](https://aka.ms/CosmosDB_OLTP_Spark_2.4_LKG) of the OLTP Cosmos DB Spark connector
