### ISSUE TITLE
Add Python wrapper and examples

### ISSUE THREAD

**Issue by dennyglee** [Azure/azure-cosmosdb-spark#3]
The connector works in Scala but we need to add examples on how it can work with PySpark.

**Comment by chhantyal** [comment]
We are using Spark Python client and this is real blocker for us to use DocumentDB

**Comment by dennyglee** [comment]
Sorry for the delay @chhantyal - we will be working on adding more of this documentation soon.

**Comment by timfpark** [comment]
@dennyglee:  Are you saying that there *is* already a Python connector that we can use and it just needs documenting?  Or does it still need to be wrapped and is unavailable?

**Comment by dennyglee** [comment]
Sorry about that, really behind on taking care of this.  You can do it right now - here's a quick example:

You would run a pySpark command similar to this:
```
pyspark --master yarn --jars /home/sshuser/jars/0.0.3c_1.12/azure-cosmosdb-spark-0.0.3-SNAPSHOT.jar,/home/sshuser/jars/0.0.3c_1.12/azure-documentdb-1.12.0-SNAPSHOT.jar
```

And then below is the query:
```
# Connection
airportConfig = {
"Endpoint" : "https://tychostation.documents.azure.com:443/",
"Masterkey" : "RL9Gmv9QC6kq0NowGPBiY4hXjuavivMVKUj3GNx8h8mYsY54AGZUySPEvYcGzFEgJIHz8RXwjgqeOjA4aZsp1w==",
"Database" : "departuredelays",
"preferredRegions" : "Central US",
"connectionMode" : "Gateway",
"Collection" : "flights", 
"SamplingRatio" : "1.0",
"schema_samplesize" : "1000",
"query_custom" : "select * from c where c.label='airport'"
}

# Create Airport DataFrame
airports = spark.read.format("com.microsoft.azure.cosmosdb.spark").options(**airportConfig).load()

# Show Aiport DataFrame
airports.show()
airports.printSchema()

# Group by Aggregate
airports.groupBy("country._value").count().show()
```

**Comment by chhantyal** [comment]
Hello @dennyglee , thanks for posting the example.

Since I commented, things have changed a bit with Azure. Does this example work with CosmosDB as well?

**Comment by dennyglee** [comment]
Yes, the above example is a referencing the Cosmos DB JARs. Thanks!

**Comment by HemanK** [comment]
Hi @dennyglee ,  @khdang,

When executing the below code in the Jupyter notebook using Pyspark kernel, I am getting an error stating pydocumentdb not found. 

Then I tried ssh-ing to the master node, and did a pip install documentdb, which installed the library, but there is no way to have Jupyter/Pyspark to use that new library as I cannot restart the process. 

I also tried to do a kill -9 to stop the pyspark process, hoping to restart pyspark, but I dont have permission to kill the process. 

So, is pydocumentdb the package that we need to connect to cosmosdb?  if so, how do we get that package to be installed? Should it be started as a Script Action when the HDInsight cluster is created?  

Heman

--- code snippet ---
import pydocumentdb
from pydocumentdb import document_client
from pydocumentdb import documents
import datetime

<img width="560" alt="pydocumentdb not found" src="https://user-images.githubusercontent.com/4811866/28294323-62bdf384-6b27-11e7-8b26-f34568328080.PNG">

<img width="898" alt="pyspark cannot be killed" src="https://user-images.githubusercontent.com/4811866/28294508-b38e8fac-6b28-11e7-815e-f636e2701081.PNG">

**Comment by dennyglee** [comment]
Hi @HemanK - for `pydocumentdb`, please note you will need to install it via [installing external packages via script action](https://docs.microsoft.com/en-us/azure/hdinsight/hdinsight-apache-spark-python-package-installation).  If you're going to use `pydocumentdb`, suggest you run from the spark-shell directly via ssh instead of running via Jupyter notebooks.

If you want to run install the Spark connector - which you can also run using python as noted in the cells above, you can follow the instructions at [Spark to Cosmos DB Connector Setup](https://github.com/Azure/azure-cosmosdb-spark/wiki/Spark-to-Cosmos-DB-Connector-Setup).

**Comment by dennyglee** [comment]
PR #72 and #73 have included Python connection via Spark connector.

**Comment by HemanK** [comment]
Thanks for the quick response, @dennyglee . And thanks for sharing the link for installing external packages via script action to install python packages. I see that the example shown is installing tensorflow on HDInsight cluster, which is really cool.  Hope to try that out at some point. 

Personally, I'd prefer to use the notebook as it enables you to do the development and testing and visualization interactively.  Is there any special reason as to why you  suggested not to use Jupyter notebooks, and instead of that to run the python code from spark-shell? 

My understanding is that the Spark Connector only supports scala and not Python. Isn't that the case?

**Comment by dennyglee** [comment]
The reason for this is because you will have to do something like the TensorFlow script action script to physically install the `pyDocumentDB` package on all of the head and worker nodes of your HDI cluster.   Once you do this, then you can use the notebook to execute using `pyDocumentDB`.

Saying this, the Spark Connector does support running via Python (i.e. PySpark).  The comments earlier in the thread denote this and we recently updated both the [readme.md](https://github.com/Azure/azure-cosmosdb-spark/blob/master/README.md) and [Azure Cosmos DB Spark Connector User Guide](https://github.com/Azure/azure-cosmosdb-spark/wiki/Azure-Cosmos-DB-Spark-Connector-User-Guide) with the python instructions.  HTH!
