### ISSUE TITLE
Issue for connecting CosmosDB MongoDB API

### ISSUE THREAD

**Issue by pwcnewmanxu** [Azure/azure-cosmosdb-spark#301]
Two issues I met
1.  When I tried to get data from element abc.dd..TransactionDetail.SaleItem,which may have no, one or more group data,  we got data something like this {@taxStructure={$t=2, $v=SINGLE_RATE}}, which is not json format. could not it be parse by json function.

2. It does not support Custom Query , right?

**Comment by rohanarora0921** [comment]
For connecting Cosmos DB's API for MongoDB to Spark, you should be using the MongoDB Spark Connector. This is to ensure that users migrating from MongoDB to Cosmos DBs API for MongoDB don't have to change a lot in their applications, including their Spark logic.

**Comment by FabianMeiswinkel** [comment]
The OLTP CosmosDB Spark connector for the SQL Api in this repository only supports the Sql Api - not Mongo or Cassandra. When you are using the Mongo or Cassandra Api in your Cosmos DB account you can use the official Mongo/Cassandra Spark connectors instead.
