### ISSUE TITLE
Unable to writeStream to CosmosDB. java.lang.ClassCastException: java.lang.Long cannot be cast to java.sql.Timestamp

### ISSUE THREAD

**Issue by ttelfer** [Azure/azure-cosmosdb-spark#303]
Unable to writeStream to CosmosDB collection.

`val incomingStream = spark.readStream.format("eventhubs").options(customEventhubParameters.toMap).load()`

`val mySchema = new StructType().add("timestamp", StringType).add("value", FloatType)`

`val messages = incomingStream.withColumn("Offset", $"offset".cast(LongType)).withColumn("Time", $"enqueuedTime".cast(StringType)).withColumn("Body", from_json($"body".cast(StringType), mySchema)).selectExpr("Time", "Body.timestamp", "Body.value").withColumn("timestamp", unix_timestamp($"timestamp", "yyyy/MM/dd HH:mm:ss").cast(TimestampType))`

`val streamingQueryWriter = messages.writeStream.format(classOf[CosmosDBSinkProvider].getName).outputMode("append").options(sinkConfigMap).option("checkpointLocation", "/tmp/streamingcheckpointlocation").start()`

`org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 2572.0 failed 4 times, most recent failure: Lost task 0.3 in stage 2572.0 (TID 89450, 10.223.101.4, executor 0): java.lang.ClassCastException: java.lang.Long cannot be cast to java.sql.Timestamp`

`at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBRowConverter$.com$microsoft$azure$cosmosdb$spark$schema$CosmosDBRowConverter$$convertToJson(CosmosDBRowConverter.scala:167) at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBRowConverter$$anonfun$internalRowToJSONObject$1.apply(CosmosDBRowConverter.scala:147) at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBRowConverter$$anonfun$internalRowToJSONObject$1.apply(CosmosDBRowConverter.scala:145) at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) at com.microsoft.azure.cosmosdb.spark.schema.CosmosDBRowConverter$.internalRowToJSONObject(CosmosDBRowConverter.scala:145) at org.apache.spark.sql.cosmosdb.util.StreamingWriteTask$$anonfun$importStreamingData$1.apply(StreamingUtils.scala:74) at org.apache.spark.sql.cosmosdb.util.StreamingWriteTask$$anonfun$importStreamingData$1.apply(StreamingUtils.scala:72) at scala.collection.Iterator$class.foreach(Iterator.scala:893) at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$11$$anon$1.foreach(WholeStageCodegenExec.scala:620) at org.apache.spark.sql.cosmosdb.util.StreamingWriteTask.importStreamingData(StreamingUtils.scala:72) at com.microsoft.azure.cosmosdb.spark.streaming.CosmosDBSink$$anonfun$addBatch$2.apply(CosmosDBSink.scala:49) at com.microsoft.azure.cosmosdb.spark.streaming.CosmosDBSink$$anonfun$addBatch$2.apply(CosmosDBSink.scala:47) at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$28.apply(RDD.scala:951) at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$28.apply(RDD.scala:951) at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2293) at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2293) at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90) at org.apache.spark.scheduler.Task.doRunTask(Task.scala:139) at org.apache.spark.scheduler.Task.run(Task.scala:112)`

**Comment by hustlestar** [comment]
Same issue. Any updates?

**Comment by mpfishe2** [comment]
Same issue. Any updates from the developers?

**Comment by FabianMeiswinkel** [comment]
Which version of the CosmosDB Spark connector was this happening with? Does it reproduce with the latest version (https://aka.ms/CosmosDB_OLTP_Spark_2.4_LKG) - I can take a look at this probably tomorrow.

**Comment by mpfishe2** [comment]
Yeah, I used the latest version (the one you specified). Apache Spark 2.4.5, Scala 2.11
