### ISSUE TITLE
Error for Cosmos DB Mongo DB process

### ISSUE THREAD

**Issue by pwcnewmanxu** [Azure/azure-cosmosdb-spark#305]
I got an error when processing Cosmos DB mongo API
java.lang.IllegalStateException: com.microsoft.azure.documentdb.DocumentClientException: com.microsoft.azure.documentdb.DocumentClientException: Invalid partition key range
--

**Comment by FabianMeiswinkel** [comment]
The OLTP CosmosDB Spark connector for the SQL Api in this repository only supports the Sql Api - not Mongo or Cassandra. When you are using the Mongo or Cassandra Api in your Cosmos DB account you can use the official Mongo/Cassandra Spark connectors instead.
