### ISSUE TITLE
Import changes : to =

### ISSUE THREAD

**Issue by mrjonlunn** [Azure/azure-cosmosdb-spark#317]
Hi,

When importing data from cosmosdb, my following column companyRange based on my JSON document suing a basic query SELECT query

```
"companyRange": [
        {
            "name": "Employee Range",
            "min": 0,
            "max": 99,
        }
```

imports in as string datatype

[{min=0, max=99, name=Employees 0-99}] 

removing the " and changes the ':' to =
I can't see in the documentation how to stop this, or just import the data as the json element?
thanks

**Comment by cjsingh8512** [comment]
You should import it as a json element
