### ISSUE TITLE
Very slow writing performance

### ISSUE THREAD

**Issue by empz** [Azure/azure-cosmosdb-spark#318]
I'm trying to write a dataframe (1M rows / 10 columns) to Cosmos DB but I'm getting extremely poor performance.

- Databricks

![image](https://user-images.githubusercontent.com/412489/59370953-f7ba0780-8d43-11e9-82c0-b7ff17548c59.png)
Using the library version from: https://search.maven.org/artifact/com.microsoft.azure/azure-cosmosdb-spark_2.4.0_2.11/1.3.5/jar

- Cosmos DB set to 10000 RU/s

Both instances are on West US 2.

It took 15 minutes to load the dataframe and the resulting container is just 1gb size.
This is extremely slow considering the high and ultra-expensive level of RU/s set (about 20 USD an hour!).

Once the documents are loaded, read performance is fast and doesn't seem to be affected by the throughput setting.

Is this the expected writing performance? Writing the same dataframe to SQL DW (Polybase) is way faster.
If it is, is there a cheaper way to load data from a dataframe to Cosmos DB?

**Comment by cjsingh8512** [comment]
Could you tell us how big is each row in the dataframe (size in kb) and what's the total data size? Please  rerun your workload and provide subscription, collection and database details on AskCosmosDb@microsoft.com and we can look into what's causing higher latency.

**Comment by jacojvv-dev** [comment]
@eparizzi I don't know if this might be related - but we also ran into slow writes when writing to Cosmos on a relatively small dataset - much (much) smaller than your dataset.

Adjusting Cosmos, Batch Size or any other related settings did not really give us any better performance - so we played around with a few different approaches until we found one that cut our write times significantly.

Here is, basically, what worked for us:

1. We performed all transforms on our dataset - up until the point where it was ready to be written to Cosmos.
2. We wrote our dataframe (that was in the format we wanted in Cosmos) to a temporary delta lake table
3. We then read the delta lake table into a new dataframe
4. Finally we wrote the dataframe that we read from the delta lake table into Cosmos (Using write.partitionBy on the same key as Cosmos)

Before doing the above the total notebook execution time was 34m 12s of which 19m was spent writing to Cosmos. After doing the above our execution time went down to 9m 30s of which 40s was spent writing to Cosmos.

We have no idea why this is the case - our best guess is that the write to Cosmos is somehow reevaluating the dataframe in some way or the other (.cache() did not help) but we are not really experts in this field - so our observations are probably wrong.

**Comment by tylerjt** [comment]
> @eparizzi I don't know if this might be related - but we also ran into slow writes when writing to Cosmos on a relatively small dataset - much (much) smaller than your dataset.
> 
> Adjusting Cosmos, Batch Size or any other related settings did not really give us any better performance - so we played around with a few different approaches until we found one that cut our write times significantly.
> 
> Here is, basically, what worked for us:
> 
> 1. We performed all transforms on our dataset - up until the point where it was ready to be written to Cosmos.
> 2. We wrote our dataframe (that was in the format we wanted in Cosmos) to a temporary delta lake table
> 3. We then read the delta lake table into a new dataframe
> 4. Finally we wrote the dataframe that we read from the delta lake table into Cosmos (Using write.partitionBy on the same key as Cosmos)
> 
> Before doing the above the total notebook execution time was 34m 12s of which 19m was spent writing to Cosmos. After doing the above our execution time went down to 9m 30s of which 40s was spent writing to Cosmos.
> 
> We have no idea why this is the case - our best guess is that the write to Cosmos is somehow reevaluating the dataframe in some way or the other (.cache() did not help) but we are not really experts in this field - so our observations are probably wrong.

I can confirm that this work around seems to be working. Originally we were writing directly from a dataframe after doing some minor transforms; this was working for a while but suddenly our ~2min batch job started running ~20mins long. 

After changing the scala code to write the transformed dataframe to datalake storage, then read that file into a new data frame and finally writing to CosmosDB. Overall job time dropped back down to the 2min range.

I would still very much like to know why there was a sudden jump in write time. Some initial investigation reveals that the DAG is very different when you compare the two methods. The 20 min write job was creating over 400 tasks in the DAG (not sure if the DAG changed since it was working normally at the beginning), while the DAG for the datalake method only has around 50 tasks.

**Comment by SandyChapman** [comment]
I was able to work around this as well by creating a new dataframe. You can skip on the delta lake workaround by doing it all in spark:

```
df_to_write = spark.createDataFrame(original_df.collect(), schema=original_df.schema)
df_to_write.write.format("com.microsoft.azure.cosmosdb.spark").mode('append').options(**writeConfig).save()
```
As long as you have enough memory on your driver node in spark to pull in your whole dataframe, this should work better. This reduced a write that was taking minutes for a single (1!!!) item to less than 3 seconds.

As noted above, `cache` doesn't seem to work.

**Comment by empz** [comment]
Less than 3 seconds for a single item is far from acceptable. This library is not mature enough to be used for anything serious.

I'm closing this since nobody is giving useful answers and we have moved away from both Databricks and Cosmos DB for our solution.

**Comment by AndresNamm** [comment]
Copy comment from here I https://github.com/Azure/azure-cosmosdb-spark/issues/382
 I recommend to look at the MAX ru's setting as this by default is 4000 (i think) at that could become the bottleneck. To understand if this is the bottleneck i suggest you to look at Throttled Requests (429s) and Normalized RU Consumption (max) metrics in your Azure
