### ISSUE TITLE
Writing a lot of documents is very slow

### ISSUE THREAD

**Issue by perthcha** [Azure/azure-cosmosdb-spark#32]
I am trying to write a lot of documents to DocDB from a data frame. However, I am getting a very bad performance. I checked DocDB metrics and the database can still handle a lot more ingress; it's just that Spark is not sending in the rows fast enough (I'm only seeing about 150-200 rows per second being written into DB but I have millions of rows in the dataframe).

As a comparison, I'm writing the same dataframe to azure blob with .write.mode(SaveMode.Overwrite).save(...) and it only takes 1 minute. Inserting these million rows to DocDB will take forever (since it only inserts 200 rows / min).

Is this a limitation of the connector, or am I doing something wrong. Here is some excerpt from my code:
```

    val config2 = Config(Map("Endpoint" -> "https://xxxx",
      "Masterkey" -> "xxxxxxx",
      "Database" -> "Statistics",
      "preferredRegions" -> "West US",
      "Collection" -> "Statistics",
      "SamplingRatio" -> "1.0"))

dataframeRows.write.mode(SaveMode.Append).documentDB(config2)
```

**Comment by dennyglee** [comment]
We're working on optimizing this code to improve the performance; will keep you updated!

**Comment by khdang** [comment]
@perthcha I've recently pushed a change to improve the writing throughput by using RX Java SDK. Can you give it try? Feel free to let us know if you're still having this issue.

**Comment by empz** [comment]
2 years later and this is still not greatly improved.

I'm writing a 5 columns/1M rows dataframe to a Cosmos DB collection and it's painfully slow.

**Comment by khdang** [comment]
That can be due to a couple of things. Since it's been a long time, can you open an issue with more details? the connector version you used, what the rate that you got. Also which region is your spark cluster and what CosmosDB region you're writing to.
