### ISSUE TITLE
String interpolation in "query_custom" failing

### ISSUE THREAD

**Issue by kodebrown** [Azure/azure-cosmosdb-spark#326]
```
val listofnodes = "'one','two','three'"
val readConfig = Config(Map(
    "Endpoint" -> "<endpoint>",
    "Masterkey" -> "<key>",
    "Database" -> "<db>",
    "Collection" -> "<collection>",
    "query_custom" -> "SELECT c FROM c WHERE  c.nodes IN $listofnodes" ))
    
val df = spark.read.cosmosDB(readConfig)
df.show()
```
Above snippet is throwing below error when i try accessing the variable.

`org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 1013.0 failed 1 times, most recent failure: Lost task 0.0 in stage 1013.0 (TID 22055, localhost, executor driver): java.lang.IllegalStateException: com.microsoft.azure.documentdb.DocumentClientException: {"errors":[{"severity":"Error","location":{"start":102,"end":103},"code":"SC1010","message":"Syntax error, invalid token '$'."}]}`

**Comment by cjsingh8512** [comment]
You need to use the Scala string interpolation to specify the query and also wrap the array in parenthesis so the server can understand it. The query should look like this:
**s"Select c FROM c WHERE c.nodes in (${listofnodes})"**. This should resolve the issue

**Comment by kodebrown** [comment]
Thanks!
