### ISSUE TITLE
Update dependency azure-documentdb to latest version (2.4.5)

### ISSUE THREAD

**Issue by sstaradubet** [Azure/azure-cosmosdb-spark#346]
There is latest version of azure-documentdb dependency (2.4.5) with some important fixes https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-sdk-java#245

**Comment by FabianMeiswinkel** [comment]
The [latest version](https://aka.ms/CosmosDB_OLTP_Spark_2.4_LKG) is using the latest versions of the underlying CosmosDB SDKs now.
