### ISSUE TITLE
HTTP 400 Upsert to SQL API

### ISSUE THREAD

**Issue by tylerjt** [Azure/azure-cosmosdb-spark#350]
When using the cosmosdb-spark connector to upsert data from SQL Server into Cosmos, I am receiving a lot of HTTP 400 error, viewable in through the Azure portal. The data seems to eventually be written to the Cosmos collection but I am curious as to why there are so many HTTP 400s. No error is thrown in my spark notebook.

Here is a sample of the config and write code:
```
val config = Config(Map(
  "Endpoint" -> "<my endpoint>",
  "MasterKey" -> "<my key>",
  "Database" -> "<database name>",
  "Collection" -> "<collection name>",
  "WritingBatchSize" -> "30"
  ,"Upsert" -> "True"
))

df.select("id","PartitionKey","col1","col2 ","col 3","col4","col5").write.mode(SaveMode.Overwrite).cosmosDB(config)
```

The writing batches result in these requests:
![image](https://user-images.githubusercontent.com/59974005/72550580-4555a000-3850-11ea-8d07-6885ed9abb18.png)

**Comment by FabianMeiswinkel** [comment]
400 indicates Bad Request - possibly conflicts or NotFound? Without being able to take a look at the concrete error you were seeing or the server-side telemetry from the account/subscription at the time when this happened I am not able to help.
