### ISSUE TITLE
Passing in a spark schema to read from cosmos db config

### ISSUE THREAD

**Issue by colanconnon** [Azure/azure-cosmosdb-spark#353]
Is there a way to pass in an existing spark schema to read from cosmos db instead of using schema sampling?

The thought is we have an existing schema defined in spark, and we can use that schema for the data frame that we get back from cosmos db.

**Comment by FabianMeiswinkel** [comment]
Yes - that works, see below sample...

import com.microsoft.azure.cosmosdb.spark.schema._
import com.microsoft.azure.cosmosdb.spark._
import com.microsoft.azure.cosmosdb.spark.config.Config
import org.apache.spark.sql._
import org.apache.spark.sql.types._

val cosmosURI = "https://XXXXX.documents.azure.com:443/"
val cosmosKey = "YourPassword"
val dbName = "Repro"

val readConfig = Config(Map(
  "Endpoint" -> cosmosURI,
  "Masterkey" -> cosmosKey,
  "Database" -> dbName,
  "Collection" -> "Data",
  "preferredRegions" -> "West Europe",
  "ReadChangeFeed" -> "true",
  "enableCrossPartitionQuery" -> "true",
  "query_pagesize" -> "1000",
  "ChangeFeedQueryName" -> "Query01",
  "ChangeFeedStartFromTheBeginning" -> "true",
  "ChangeFeedUseNextToken" -> "true",
  "RollingChangeFeed" -> "true",
  "InferStreamSchema" -> "false",
  "ChangeFeedCheckpointLocation" -> "/mnt/bookmarks_schematest/read_cf_source",
  "changefeedmaxpagesperbatch" -> "10"
))

val documentSchema = StructType(Array(
    StructField("id", StringType),
    StructField("name", StringType),
    StructField("value", DecimalType(10,2))))
  
val changeFeedRead = spark.read.schema(documentSchema).cosmosDB(readConfig).persist()
print(" - Number of Change Feed Records (ORIGINAL) = ", changeFeedRead.count())

changeFeedRead.show()
print("SCHEMA")
print(changeFeedRead.schema)

changeFeedRead.unpersist()
