### ISSUE TITLE
MapType not working in streaming 

### ISSUE THREAD

**Issue by realAngryAnalytics** [Azure/azure-cosmosdb-spark#355]
. When using Streaming with a MapType in a struct I get the following error:
 
org.apache.spark.SparkException: Job aborted due to stage failure: Task 20 in stage 75.0 failed 4 times, most recent failure: Lost task 20.3 in stage 75.0 (TID 2473, 10.139.64.20, executor 5): java.lang.ClassCastException: org.apache.spark.sql.catalyst.expressions.UnsafeMapData cannot be cast to scala.collection.immutable.Map
 
This happens in com.microsoft.azure.cosmosdb.spark.streaming.CosmosDBSinkProvider"
 
But not in: com.microsoft.azure.cosmosdb.spark

**Comment by Strabox** [comment]
There is any kind of target date for this issue?

**Comment by jenden** [comment]
I'm also interested in this issue. It would be convenient to write a Map[String, String] directly to JSON in Cosmos. I'm using `to_json` to cast the Map to a String but the result is then stored in a string in the Cosmos sink which is less than ideal.

**Comment by revinjchalil** [comment]
This has been fixed in version 3.3.4 and the corresponding uber jar can be downloaded from [here](https://search.maven.org/search?q=a:azure-cosmosdb-spark_2.4.0_2.11)

The details of the fix can be found in this [PR](https://github.com/Azure/azure-cosmosdb-spark/pull/412)
