### ISSUE TITLE
Invalid JSON String error when connecting through Databricks

### ISSUE THREAD

**Issue by jaspreetwaraich** [Azure/azure-cosmosdb-spark#373]
I am trying to connect to Cosmos DB Mongo API from Databricks and I get the error,

`java.lang.IllegalStateException: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Invalid JSON String: &#39;&#39;`

I tried these options,
Option 1:
`data = spark.read.format("com.microsoft.azure.cosmosdb.spark").option("Endpoint", "https://cosmosdb-myendpoint.com:443/").option("Masterkey", "primary key of the account").option("Database", "sample").option("Collection", "sample1").load()
`
Option 2:
```
cosmosConfig = {
  "Endpoint" : "https://cosmosdb-myendpoint.com:443/",
  "Masterkey" : "primary key of the account",
  "Database" : "sample",
  "Collection" : "sample1"
}
cosmosdbConnection = spark.read.format("com.microsoft.azure.cosmosdb.spark").options(**cosmosConfig).load()

```
Both these options give the same invalid JSON string error. I've already installed the JAR azure-cosmosdb-spark_2.4.0_2.11-2.1.2-uber.jar on the cluster.

**Comment by FabianMeiswinkel** [comment]
The Azure CosmosDB Spark connector "com.microsoft.azure.cosmosdb.spark" is a connector for the SQL API only.

For Mongo/Cassandra the native Spark connectors need to be used (see https://docs.microsoft.com/en-us/azure/cosmos-db/spark-connector)
