### ISSUE TITLE
How to query change feed?

### ISSUE THREAD

**Issue by ankushreddy** [Azure/azure-cosmosdb-spark#39]
Hi Team from the documentation of the changefeed we see that we can query using spark. is there any example that I can look into or if there is any other way to get the latest changes in the documendb.

Thanks,
Ankush Reddy.

**Comment by khdang** [comment]
@ankushreddy We've checked in the changes to support reading CosmosDB change feed. For sample usage you can look at the unit tests at https://github.com/Azure/azure-cosmosdb-spark/blob/98cd786f1cd563c89cdba9f883b8aa8754fdf0ab/src/test/scala/com/microsoft/azure/cosmosdb/spark/schema/CosmosDBDataFrameSpec.scala#L114

Feel free to let us know if you have any questions.
