### ISSUE TITLE
Upsert documents

### ISSUE THREAD

**Issue by perthcha** [Azure/azure-cosmosdb-spark#40]
I'm using the below command to write documents from spark:

myDataframe.coalesce(40).write.mode(SaveMode.Append).documentDB(readConfig2)

This simply inserts documents into DocDB. 

Is it possible to do an UPSERT with this connector (i.e. For each document, insert the doc when not exists, or updates the doc with the same id if it exists.)?

**Comment by perthcha** [comment]
I think I found the upsert option in the config. Will try this out:

https://github.com/Azure/azure-cosmosdb-spark/blob/master/src/main/scala/com/microsoft/azure/cosmosdb/spark/config/CosmosDBConfig.scala

**Comment by khdang** [comment]
@perthcha Great. Let us know if you have any issues.
