### ISSUE TITLE
Can't query Cosmos DB from Spark when Cosmos DB is behind PrivateLink

### ISSUE THREAD

**Issue by mpfishe2** [Azure/azure-cosmosdb-spark#402]
Getting the following error when trying to query Cosmos DB behind a PrivateLink from Azure Databricks which is peered correctly.

"org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 28, 10.140.16.124, executor 0): java.lang.IllegalStateException: com.microsoft.azure.documentdb.DocumentClientException: Direct mode https protocol is not currently supported with PrivateLink. Please use Direct mode TCP protocol instead."

How do we "use Direct mode TCP protocol"?

**Comment by FabianMeiswinkel** [comment]
Direct TCP is not supported for batch operations (which still use the sync V2 java SDK). You can use Gateway mode (set the "connectionmode" property to Gateway in the config) --> https://github.com/Azure/azure-cosmosdb-spark/wiki/Configuration-references

**Comment by mpfishe2** [comment]
@FabianMeiswinkel  thanks! That worked! Much appreciated.

**Comment by mpfishe2** [comment]
Just as a note for anyone running into trouble with this, not only should you change the "connectionmode" to "Gateway", but if you are using Databricks and testing this out in a Notebook you may want to restart your cluster.

Not sure why, but initially this fix did not work until I restarted my cluster.
