### ISSUE TITLE
Azure Cosmos DB Apache Spark Connector for Core (SQL) API for Spark 3.x version in databricks

### ISSUE THREAD

**Issue by mahammada** [Azure/azure-cosmosdb-spark#444]
Hi Team,

Can you please update when we expect Cosmos db spark connector jar file which supports Spark 3.x version since Databricks runtime version for 6.4 is getting end of support on April 1st 2021 but till now we don't have Cosmos DB connect for Spark not available for Spark 3.x version. Kindly provide us an update when we can expect Cosmos DB Spark connector for Spark 3.x version. If it is already available please do update without fail.

Note: Currently we are in the process move our build to DBR 7.4 version which supports Spark 3.x version.

Thank you in anticipation!!

Best Regards,
Mahammad Khan
+91-9885360726

**Comment by ghost** [comment]
+1

**Comment by jaokeeffe** [comment]
Yep - many customers waiting on this eagerly! Appreciate the work involved - any updates? Thanks!

**Comment by TissonMathew** [comment]
What's the ETA on Spark 3 support?

**Comment by todddube** [comment]
ETA

**Comment by FabianMeiswinkel** [comment]
The new Cosmos DB Spark connector has been released. The Maven coordinates (which can be used to install the connector in Databricks) are "**com.azure.cosmos.spark:azure-cosmos-spark_3-1_2-12:4.0.0**"

The **source code** for the new connector is located here: https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/cosmos/azure-cosmos-spark_3-1_2-12 

A **migration guide** to change applications which used the Spark 2.4 connector is located here: https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/cosmos/azure-cosmos-spark_3-1_2-12/docs/migration.md

**The quick start introduction:** https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/cosmos/azure-cosmos-spark_3-1_2-12/docs/quick-start.md
**Config Reference:** https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/cosmos/azure-cosmos-spark_3-1_2-12/docs/configuration-reference.md
**End-to-end samples:** https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/cosmos/azure-cosmos-spark_3-1_2-12/Samples/Python/NYC-Taxi-Data/01_Batch.ipynb
