### ISSUE TITLE
Question - dose this connector work with java SpringBoot?

### ISSUE THREAD

**Issue by ImAbhishekTomar** [Azure/azure-cosmosdb-spark#472]
Does this connector work with java spring boot? If work, Please share some sample.

**Comment by FabianMeiswinkel** [comment]
This repository is for the Cosmos DB connector for Apache Spark 2.* - as fas as I can tell there is no integration/connection between Spark and Spring Boot - different runtimes/frameworks used for different use cases. Apache Spark allows running analytic jobs and make it easy to distribute the load across multiple nodes. While Spring Boot tries to simplify UI application and microservice development.

So, unless you try to host Apache Spark within your SpringBoot application or something similar - no, this connector does not work with Spring Boot - but Apache Spark 2.* instead.
