### ISSUE TITLE
jars provided in releases directory don't seem to work.

### ISSUE THREAD

**Issue by dp-farm** [Azure/azure-cosmosdb-spark#49]
We could not build jars using `mvn clean package` because of this issue `https://github.com/Azure/azure-cosmosdb-spark/issues/48`

So we tried using jars provided in releases directory and get this error while using example given in README.

This is how I use jars.
```bash
ubuntu@devesh-170:~/hadoop_experiment/spark-2.1.1-bin-hadoop2.7$ bin/spark-shell --jars /home/ubuntu/hadoop_experiment/azure-cosmosdb-spark/releases/azure-cosmosdb-spark-0.0.3_2.0.2_2.11/azure-cosmosdb-spark-0.0.3-SNAPSHOT.jar,/home/ubuntu/hadoop_experiment/azure-cosmosdb-spark/releases/azure-cosmosdb-spark-0.0.3_2.0.2_2.11/azure-documentdb-1.10.0.jar
``` 

This is the error -->
```scala
scala> val coll = spark.sqlContext.read.cosmosDB(readConfig2)
java.lang.NoClassDefFoundError: org/json/JSONException
  at java.lang.Class.getDeclaredFields0(Native Method)
  at java.lang.Class.privateGetDeclaredFields(Class.java:2509)
  at java.lang.Class.getDeclaredField(Class.java:1959)
```

**Comment by khdang** [comment]
@dp-farm The reason you're seeing this is because the CosmosDB Spark connector jar and CosmosDB Java SDK jar don't include the dependencies such as JSON. 

To resolve this issue, you can either run Spark from an Azure HDInsight cluster which is provisioned with all the necessary jars, or you can also compile the Spark Connector and use the jar with all the dependencies.

**Comment by khdang** [comment]
I'm closing this - please reopen if you need further help on this.

**Comment by dennyglee** [comment]
Please note, another way to avoid this issue is to include the JSON using --jars.  Specifically the command would be something like:
```
spark-shell --master yarn --jars /$location/json-20090211.jar
```

You can download the jar from maven at [JSON in Java >> 20090211](https://mvnrepository.com/artifact/org.json/json/20090211).
