### ISSUE TITLE
Create script action to copy the azure-cosmosdb-spark JARs to all HDI head and worker nodes

### ISSUE THREAD

**Issue by dennyglee** [Azure/azure-cosmosdb-spark#79]
Create a script action similar to the one documented in [Use Script Action to install external Python packages for Jupyter notebooks in Apache Spark clusters on HDInsight](https://docs.microsoft.com/en-us/azure/hdinsight/hdinsight-apache-spark-python-package-installation); specifically the [TensorFlow Install Script Action](https://hdiconfigactions.blob.core.windows.net/linuxtensorflow/tensorflowinstall.sh).

**Comment by AnisTss** [comment]
I recommend this !!
I spent 2 days with no result trying to configure HDInsight spark cluster to use the connector.
I need a more detailed guide or a script action until i get to know the spark environment as i should.
