### ISSUE TITLE
java.net.SocketException: Connection reset errors

### ISSUE THREAD

**Issue by dennyglee** [Azure/azure-cosmosdb-spark#89]
When reading or writing to Cosmos DB from the Spark connector, would get intermittent `java.net.SocketException: Connection reset errors` significantly slowing the overall query / write performance for that one or two threads.

**Comment by khdang** [comment]
I'm finding a consistent way to reproduce this issue. So far reading and writing 100GB to 450GB (19-67millions) documents on 4 work nodes cluster (32 cores, 28 * 4 Gb of memory) don't have this issue.

**Comment by khdang** [comment]
This could be related to the default small connection pool size of 100. We can try to increase this to a larger number with connectionmaxpoolsize configuration.

**Comment by nomiero** [comment]
This is resolved now
