### ISSUE TITLE
Running local Spark cluster results in error

### ISSUE THREAD

**Issue by dennyglee** [Azure/azure-cosmosdb-spark#90]
Running from a local Spark cluster results in the error:
```
scala> val coll = spark.read.cosmosDB(readConfig2)
java.lang.NoClassDefFoundError: org/json/JSONException
  at java.lang.Class.getDeclaredFields0(Native Method)
  at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
```

If you include the `json-20090211.jar` in the `--jars` it will work.  But this means we have a bug to determine whether we need to explicitly include the jar.

**Comment by tknandu** [comment]
Closing after resolving issue #96
