### ISSUE TITLE
Include in User Guide / sample scripts how to save to Cosmos DB

### ISSUE THREAD

**Issue by dennyglee** [Azure/azure-cosmosdb-spark#91]
While the example to write to Cosmos DB is in [CosmosDBDataFrameSpec.scala](https://github.com/Azure/azure-cosmosdb-spark/blob/f8ec20b4a2108e242167b7779db24743abbf56a3/src/test/scala/com/microsoft/azure/cosmosdb/spark/schema/CosmosDBDataFrameSpec.scala) - this is not at all obvious.  Should provide write example directly in readme.md and user guide.

To save a DataFrame to Cosmos DB based on the flights example used thorughout this documentation:
```
// Import SaveMode so you can Overwrite, Append, ErrorIfExists, Ignore
import org.apache.spark.sql.{Row, SaveMode, SparkSession}

// Create new DataFrame `df` which has slightly flights information 
// i.e. change the delay value to -999
val df = spark.sql("select -999 as delay, distance, origin, date, destination from c limit 5")

// Save to Cosmos DB (using Append in this case)
//    Ensure the baseConfig contains a Read-Write Key
//    The key provided in our examples is a Read-Only Key
df.write.mode(SaveMode.Append).cosmosDB(baseConfig)
```

**Comment by dennyglee** [comment]
Forgot to note here's the Python version of it:
```
df.write.format('com.microsoft.azure.cosmosdb.spark').mode('overwrite').options(**writeConfig)
```

**Comment by pl7y** [comment]
I read through available documentation but I couldn't really find anything related to how to **generate a graph in spark (using gremlin inside it?) and persist it to graph cosmosDB**. Am I missing something?

**Comment by ttelfer** [comment]
@dennyglee 

Any reference material for what should be found in **writeConfig?

**Comment by ttelfer** [comment]
Is there any special configuration required when CosmosDB is setup to work with the MongoDB wire protocol?

**Comment by dennyglee** [comment]
@pl7y By any chance are you referring to [Azure Cosmos DB: Perform graph analytics by using Spark and Apache TinkerPop Gremlin](https://docs.microsoft.com/en-us/azure/cosmos-db/spark-connector-graph)

**Comment by dennyglee** [comment]
@ttelfer You should be able to use mongo-spark directly if you're using the the Cosmos DB Mongo API.  The `azure-cosmosdb-spark` connector focuses on the Cosmos DB SQL API.  HTH!

**Comment by dennyglee** [comment]
@ttelfer for **writeConfig, please refer to https://github.com/Azure/azure-cosmosdb-spark/wiki/Configuration-references.  We're in the process of updating our documentation to help find these things easier.

**Comment by dennyglee** [comment]
Okay, closing this GitHub issue for now.  Thanks!

**Comment by jangcy** [comment]
@dennyglee 
Hi Denny!
In Python version you provided: 
`df.write.format('com.microsoft.azure.cosmosdb.spark').mode('overwrite').options(**writeConfig)`
there is no save() method at the end. Should it be there, or not?

If I use below command:
`newDf.write.format('com.microsoft.azure.cosmosdb.spark').mode('append').options(**writeConfig)`
This is what Jupyter Notebook gives me as response:
`<pyspark.sql.readwriter.DataFrameWriter object at 0x7f8c93bb7828>`
Is this a valid response and I should be able to see document in Cosmos?

Thanks!

**Comment by jangcy** [comment]
Hi Denny.
Thanks for your answer - that's what I thought.
Nevertheless, adding .save() to my code is producing me an error, that I cannot handle by myself. Could you please look at it as I described it here: [stack thread](https://stackoverflow.com/questions/49669292/upsert-to-cosmosdb-from-spark-error)

Oh, and you have missed .save() in your second post in this issue here :)
![image](https://user-images.githubusercontent.com/38102316/38393767-2369cba8-392c-11e8-99e0-da3b61b15f14.png)

**Comment by dennyglee** [comment]
Got it - thanks for catching that!  I'll take a look at the stack thread now!

**Comment by cmadhu00** [comment]
df.write.mode(SaveMode.Append).cosmosDB(writeConfig)

Not working.

It's giving java.lang.NoSuchMethodError

Thanks in advance for the help!

I am using DataBricks Spark.. 

Just i want load DataFrame Data to Cosmos Db

**Comment by himaniR** [comment]
Hi @cmadhu00 did you find any resolution to same? I am facing same issue.

**Comment by zpappa** [comment]
> @ttelfer for **writeConfig, please refer to https://github.com/Azure/azure-cosmosdb-spark/wiki/Configuration-references. We're in the process of updating our documentation to help find these things easier.

This is not clear in the current documentation, nor is it clear that the documentation for this connector is only for SQL. I spent a lot of time trying to make this work only to realize I had to use spark-mongo!
