### ISSUE TITLE
Provide a way to rate control the spark connector to never go more than a specific limit

### ISSUE THREAD

**Issue by khdang** [Azure/azure-cosmosdb-spark#98]

**Comment by dennyglee** [comment]
In the interim, let's document a scenario using the flights data so example (100K and 250K RUs | 4 worker nodes Spark cluster with default and modified Spark configuration).  So this way users can modify the requests per second configuration within the Config.  

The modified Spark configuration would be:
"executorMemory": "8G", 
  "executorCores": 4, 
  "numExecutors": 4, 
  "driverCores": 2,

**Comment by tknandu** [comment]
Update: While writing to Cosmos DB using bulk import, you can now set write throughput budget using 'WriteThroughputBudget' with version 1.1.2+

**Comment by tknandu** [comment]
Related to issue #139

**Comment by sagarsharmas** [comment]
Even if I have a collection with 10,000 RUs, and I provide "8000" as WriteThroughputBudget in the writeConfig, it still provides "Request rate too large" message. What is the correct way to use WriteThroughputBudget, and what is the max that we can provide for a collection with 10,000 RUs?

**Comment by DanHamlin-LifeTime** [comment]
Does this feature play well with Autoscaling collections?  It seems as though this setting is having no effect when we set it.
